import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '../components/navbar'
import Footer from '@/components/footer'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>

			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={``}>
				<div className={`${styles.header} ${styles.header_image}`}>
					<div className={styles.content_header}>
						{/* <!-- <img src="${require('./css/sibghatallah-03.png')}" alt=""> --> */}

						<div className={styles.bgImgCon}>
							<Image
								className={styles.bgImg}
								src="/gBG2.png"
								layout="fill"
								objectFit="cover"
								sizes="100vw"
								alt='bg'
							/>
						</div>

						{/* <div className={styles.sib}></div> */}
						{/* <Image src="/sibghatallah-03.png" width="20%"/> */}
						<div className={styles.sibBox}>
							<Image src="/sibghatallah-03.png" alt="sib" height={200} width={1000}/>
							<label className={styles.subtitle}>
								The colors of Allah, And there is nothing better than the colors of Allah. (Surah al Baqarah, 138)
							</label>
						</div>

					</div>
					<div class="titlediv">
						<div class="centered-text title">
							<h1 id="mainTitle">Manzar-e-Mussawir</h1>
							<label>Art Gallery & Expo</label>
						</div>
					</div>
					<div class="dates">
						<div class="infoDiv">
							<label>February 10th 2024</label>
						</div>
						<div class="infoDiv">
							<a href="https://goo.gl/maps/GiWyGWR3v3bKHqZKA" target="_blank"><label>Masjid-e-Mohammedi, Houston</label></a>
						</div>
					</div>
				</div>
			</main>
		</>
	)
}
